### ISSUE TITLE
Kui asutusel on mitu DHSi?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#1]
Nt Tallinna linnal.

**Comment by andreskytt** [comment]
Mitu võimalust. Võib leppida kokku nimeruumides stiilis asutusekood/DHS/allasutusekood/SendDocument. Aga see eeldab, et saatja ka teab, millist neist mitmest DHSist ta kasutada tahab. Mis Tallinna linna puhul ei pruugi nii olla aga Tartu Ülikooli kolledgite puhul ehk küll. Ehk, Tallinna puhul on vast mõistlikum, kui nad üle x-tee eksponeerivad vaid ühte DHSi ning jagavad dokumente sealt edasi kas automaatselt või käsitsi.

Sama teema on üleval olnud seoses e-arvetega ja on leitud, et riikliku tegevuskohtade registrit pidama hakata ei ole mõistlik.

**Comment by PriitParmakson** [comment]
Jah, üks peab olema ekponeeritud ja sinna saatmisega on saatja oma saatmiskohustuse täitnud. Kui on erivajadus dokumendivoogusid jagada, siis  seda saab korraldada dokumendi edasisaatmisega asutuse ühest DHS-st teise või poolte kahepoolse kokkuleppega - need väljuvad siinse protokolli  skoobist.

Mitme DHS-i puhul tekiksid ka semantilised küsimused nagu millised on "valesse" DHS-i saatmise õiguslikud tagajärjed, kuidas tõlgendada sama dokumendi korraga kahte DHS-i saatmist jms - millele üldarusaadavaid vastuseid oleks raske ja keerukas määratleda.

**Comment by tormi** [comment]
Tere. Mis siis, kui mingi valdkonna infohaldus on korraldatud ilma asutuste DHS-ideta ja dokumendid on kättesaadavaks tehtud asutusteüleses valdkonnapõhises rakenduses?

Näiteks riigitöötaja iseteenindusportaali [kinnitusdokumentide register](https://www.riigitootaja.ee/rtip-client/public/document-registry/), kus avaldatakse riigitöötajate puhkuse- ja lähetusdokumendid. Neid dubleerivalt asutuste DHS-idesse enam ei kanta.

Näeme seda võimalusena ka kinnisvaravaldkonna infohalduse tõhusamaks muutmiseks, https://github.com/kinnisvara/infohalduse-tegevuskava/issues/14.

See põhimõte kajastub [AvTS eelnõu](https://eelnoud.valitsus.ee/main/mount/docList/a4d3c76c-64d3-4db3-b2f2-dff4d6f9c500) § 2 punktis 7:
![avts_ 2_p7](https://cloud.githubusercontent.com/assets/146800/10724061/fa2c0c46-7bc9-11e5-875b-989b28563d30.PNG)
@liivi-mkm, @andreaspapp, @rristo

**Comment by liivi-mkm** [comment]
Ma pole küll kindel, miks viimati tõstetud teema on sama, mis eespool kirjeldatud. 
Jah, kui asutused toimetavad teises infosüsteemis, siis ei ole mõistlik avalikustamiseks vms infot DHSi dubleerida. Seda võimalust on kasutatud ka praegu, reguleerides selle eriseadusega.
Pean siiski vajalikuks veel kord öelda, et sel juhul tuleb lihtsustada ka protsesse, töötada pigem andmete kui dokumentidega jne. Iga dokumendiliigi jaoks oma DHS pole lahendus.
Avalikustamisest. Riigitöötaja iseteenindusportaali puhul oli algselt plaanis lahendada avalikustamine andmete avamisega. Võimalus teha erinevaid päringuid, sh koondatult - nt N asutuse lähetuskulud X aastal vms. Kahjuks asus Justiitsministeerium tookord seisukohale, et RTIPi dokumendid kui õigusaktid (üksikaktid, s.t käskkiri, korraldus) tuleb avalikustada dokumentidena ja dokumendiregistris. Ei olnud ka eriseadust, kus sätestatud teisiti. Siiski on ilmne, et saaks ka paremini.

**Comment by tormi** [comment]
> Iga dokumendiliigi jaoks oma DHS pole lahendus.

Ma viitasin valdkonnale, mitte dokumendiliigile. RTIP tegeleb riigi [tugitegevuste](http://www.rtk.ee/organisatsioon/rtip) valdkonnaga, hetkel on realiseeritud _lähetuse_,  _puhkuse_ ja _varahalduse_ menetlused, aga tõenäoline on, et lisandub veel.

**Comment by liivi-mkm** [comment]
RTIP ei ole klassikaline DHS. See oli minu märkuse mõte.

**Comment by tormi** [comment]
Minu mõte oli, et tulekski enam liikuda asutuste silotornidest (klassikaline DHS) RTIP-i taoliste valdkonnapõhiste lahenduste suunas.

Minu küsimus on, kas ja kuidas sellistel juhtudel lahendada kandes püstitatud probleem, st dokumentide pushimine mingi asutuse suunas juhul, kui asutus haldab mingeid dokumente põhiDHS-ist eraldi, antud juhul asutusteüleses valdkonnapõhises infosüsteemis (EHR, RTIP, KVR jne). Sisuliselt otsin vastust [protokolli motivatsiooni peatüki](https://github.com/e-gov/DHX/blob/master/Protokoll.md#motivatsioon) punktis 4 esitatud küsimusele:

> Laienev dokumendiringlus ja dokumente vahetavate infosüsteemide tihenev võrgustik (dokumendivahetus tänapäeval ei piirdu „puhaste“ DHS-dega – dokumente vahetavad ka infosüsteemid, kus dokumendihaldus klassikalises mõttes on ainult üks andmetöötluse liik) nõuab alternatiivi ühe keskse postkastiserveri kaudu toimuvale dokumendiliiklusele.

**Comment by PriitParmakson** [comment]
Üks tähelepanek, mille üle peaks mõtlema on see, et mitte ainult DHSid ei kasuta DVK-d - EK

**Comment by PriitParmakson** [comment]
seega on muudatuse skoop laiem Kertu äkki saab näha, mis süsteemid kasutavad - KH

hmm, see oleks sisuliselt DVK kasutajate list, mille registrikood ei ole tavaline asutuse registrikood. Aga kui mingi süsteem küsib andmeid siiski vaid asutuse sertifikaadi alusel, siis pole meil kuidagi võimalik välja võtta, milline infosüsteem neid päringuid täpsemalt saadab. -KH

**Comment by PriitParmakson** [comment]
Saatev süsteem ei pea tingimata olema DHS. Selguse mõttes peaksime selle selgituse protokolli lisama.

Seetõttu, kui praegu on süsteeme, mis saadavad DVK-sse dokumente ja nende DVK kasutus piirdub saatmisega, siis siin ei ole takistusi. Need süsteemid peavad realiseerima endal DHX saatmisfunktsionaalsuse (looma DHX saatmisvõimekuse).

Keerulisem on küsimus süsteemidega, kes dokumente tahavad vastu võtta, kuid ei defineeri end DHS-dena.

Keegi ei keela neil dokumente vahetada, nad võivad kasutada ka sendDocument teenusemustrit. Probleem saab olema nende süsteemide ülesleidmises. Universaalset lahendust siin teha on halduslikult oluliselt kulukam.

Vajame DHS-i definitsiooni. Definitsioonist peab selguma ka see, kas asutusel võib olla üks või mitu DHSi. Teiseks vajame teavet, kui palju selliseid mitme DHSi asutusi reaalselt on ja miks nad mitut süsteemi kasutavad. Siis saab vaadata, mis on vajadus ja kuidas DHX võiks seda rahuldada.

Praegu on DHX projekteeritud universaalse, minimaalse adresseerimissskeemina.

Aluspostulaadiks on see, et asutusel on DHX mõistes üksainus DHS. See on määratud fikseeritud tähendusega alamsüsteemi nime "DHX" kaudu.

Nimetuse "DHX" kaudu on asutuse DHS X-teel kergesti ülesleitav.

Kui soovime, et asutusel oleks mitu süsteemi, mis DHX sendDocument teenuste abil dokumente vastu võtaksid, siis tekib see probleem, et neil ei saa kõigil olla sama alamsüsteemi nimi ("DHX"). Neil ei ole keelatud sendDocument teenust teha ja nende kaudu dokumente vahetada, kuid DHX adresseerimisskeemis neid näha ei ole.

Kas võiks olla alternatiive? Jah, võimalik oleks fikseerida teenusenimi - nt "DHXsendDocument" ja lugeda, et kõik alamsüsteemid (ükskõik, mis nimega), kes DHXsendDocument teenuse loovad, on DHX dokumendivahetuse skeemis osalejad. Siin tekib aga see probleem, et kõiki samanimelisi teenuseid - konkreetselt "DHXsendDocument" üles leida on keerukam.

Sa tahad dokumenti saata ja tead adressaadi registrikoodi. Aga millise alamsüsteemi all tal "DHXsendDocument" võiks olla? Seda ei leia ainuüksi X-tee globaalse konfiguratsiooni põhjal (glob-konfis on ainult alamsüsteemide nimed), peaks hakkama pärima turvaserveritest või kasutama RIHA. RIHA ei paku veel täielikku X-tee teenuste nimekirja masinloetaval kujul.
