### ISSUE TITLE
DHS on ehitatud omas rütmis DVK-s dokumente võtmas käima. Tal pole jõudlust korraga palju dokumente vastu võtta.

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#11]
Lahenduseks võib olla Universaalsesse tarkvarakomponenti sõnumijärje funktsionaalsuse lisamine.

**Comment by aleksei-kokarev** [comment]
kas sõnumijärje funktsionaalsuse all mõeldud just mq tarkvara(ntks activeMQ) või mõledud lihtsalt mõte et UK hoiab sõnumeid mingi aeg ja kui DHS küsib siis annab neid? Seda võib realiseerida ntks andmebaasiga, mitte päris MQ-ga.

**Comment by PriitParmakson** [comment]
Mõeldud on funktsionaalsust, mitte konkreetset tarkvara. Palun uurige, millist teeki või komponenti kasutada ja tehke ettepanek. Me peaksime tegema võimalikult lihtsa lahenduse. Võib-olla sobibki andmebaas paremini.

**Comment by PriitParmakson** [comment]
Täiendav teave. Palun uurige Apache ActiveMQ kasutamist ja kui ei ole veenvat põhjendust midagi muud valida, siis kasutamegi seda.

**Comment by andreskytt** [comment]
Kui UK teeb pushi (nagu ta peaks), siis on mõistlik kasutada PGQd. See toimib otse baasis (kui kasutatakse Postgred) ja lahendab persistentsuse probleemi küllalt elegantselt. Liiatigi on tema implementatsioon liidese mõttes suhteliselt lihtne: kui postgre miskil põhjusel kasutatav ei ole, saab lihtsalt mockida sama funktsionaalsuse mis iganes baasile. Meie mahtude juures ei ole lihtne tabelisse kirjutamine ja kustutamine jõudluse mõttes probleemiks. 

Kui sihuke funktsionaalsus ei olnud protokolli disaini faasis plaanis, siis tuleb protokolli oluliselt täiendada. Sõnumiedastuse kutse semantika muutub täielikult. Enne oli "Dokument kätte saadud". Nüüd "Dokument vastu võetud DHSile edasi andmiseks".

**Comment by PriitParmakson** [comment]
RIA infraosakonna soovitusel lähtume Apache Active MQ-st.
Paigaldamisel on variandid: 
• apt-get install activemq  
• wget  blaah.tar.gz  ja pakid lahti töökataloogi 
• Kasutad tomcati sees integreerituna
• TomcatEE variant, mis on täisintegreeritud lahendus.
HA tugi on builtin. http://activemq.apache.org/clustering.html
Üks lisaboonus veel – see oskab dockerina ka käia :)
- \- 
  Andres,
  UK on rangelt piiritletud kui abistav komponent, mida DHSi arendaja/haldaja võib oma DHSi sisse lõimida, aga võib ka mitte. Sõnuedastuse semantika ei sõltu UK kasutamisest või mittekasutamisest.
