### ISSUE TITLE
Kas ikka saab läbi ühe teenusega? Näiteks kinnitus dokumendi kättesaamise kohta

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#12]
Seda näitab protokolli täiendav analüüs ja verifitseerimine. Kavandatud funktsionaalsus katab dokumendivahetuse põhivajaduse. Täiendavate omaduste lisamisel peab vaatama, millisesse kihti omadus läheb.

X-tee mõttes on piisavaks ja pidavaks kinnituseks dokumendi kättesaamise kohta X-tee päringu vastus (_Response message_). Kui soovitakse "kõrgema taseme" s.t äritaseme kinnitust, siis see saab tulla ainult DHS-st. Äritaseme kinnituse võib teostada DHX dokumendina. Sellise käitumismustri võib vormistada eraldi kihina; ei pea tingimata olema DHX-i osa.

**Comment by tonupold** [comment]
Kinnitus dokumendi kättesaamise kohta võib olla erineval tasemel:
- Kinnitus et dokumendi kapsel salvestati vastuvõtja poolt (kapsilt veel ei töödeldud,  kuigi teostati esialgne valideerimine). Seda pakub DHX protokoll sendDocuments teenuse sünkroonse vastusena.
- Kinnitus et dokument hõlmati DHS süsteemi (aga veel ei registreeritud,paljud DHS-id teostavad hõlmamise ja registreerimise koos)
- Kinnitus et dokument registreeriti DHS poolt (sai registreerimise numbri, kausta jms)

Äripoolelt tundub et kaunis suur nõudlus on "Dokument registreeriti" sündmuse jaoks (saatjale tagasi).
Väljad mis sellises teenuses võiksid olla on:
- Vastuvõtja registreerimise nr
- Dokumendi staatus (staatuste ühtlustamine probleem)

Registreerimise staatuse tagasi saatjale saatmine uue DHX/Kapsel 2.1 dokumendina aga tundub problemaatiline, sest:
- hetkel kapsel on mõeldud dokumendi saatmiseks, mitte staatuse saatmiseks. Kapslis on paljud kohustuslikud väljad "Tähtaeg", "Juurdepääsu piirang" jne, mis registreerimise staatuse jaoks ei oma tähendust.
- saatja peab omal samuti välja arendama DHX  sendDocuments teenuse. Hetkel DHX protokolli järgi see saatjal nõutud ei ole.

Alternatiiv oleks siin mõelda läbi, kas lisada DHX protokolli nõue et vastuvõttev süsteem VÕIB pakkuda teenust getDocumentStatus või getRegistrationStatus? 
Kui selline teenus kasutusele võtta siis tuleks kirjeldada ka turvalisuse nõuded: vastuvõttev süsteem peab kontrollima et getDocumentStatus päring tuli originaal dokumendi saatjalt.

**Comment by PriitParmakson** [comment]
Siin peaks pöörduma ITAO kui dokumendihalduse koordinaatori poole, tutvustada kogutud andmeid ja küsima ITAO arvamust. Vajaksime standardimise mandaati, et neid interaktsioone protokolli sisse kirjutada.
