### ISSUE TITLE
Kas puhverdamine võiks toimuda TS tasemel?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#2]
Kas puhverdamine võiks toimuda TS tasemel? Algselt oli X-teel nii kavandatud („asünkroonne X-tee“) – teave Ahti Kelderilt.

**Comment by andreskytt** [comment]
Ei. Puhverdamine on oma olemuselt keeruline ja operatiivselt nõudlik ülesanne. Võib pakkuda standardset tarkvara mõne enamlevinud järjekorratarkvara peale aga oma olemuselt realiseerib turavserver teatavat turvalist protokolli. Puhverdamine on aga transpordi küsimus. Lisaks võib ette näha suurt hulka erinevaid puhverdamis- ja uuesti proovmise strateegiaid mis sõltuvad olulisel määral organsiatsioonist.

**Comment by PriitParmakson** [comment]
Vrdl 

> Finland has adopted the following rule: Security server must be security server and nothing else.
