### ISSUE TITLE
Mismoodi DHX puhul käib asutusel selle teenuse avamine asutustele?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#21]
Mis moodi DHX puhul käib selle teenuse avamine asutusel asutustele? Kas iga asutus peab seda ise iga kontakti puhul eraldi tegema? Nö. andma loa oma teenusele?

X-teel on võimalus avada teenus kõigile. Praegu on nii mõeldud.

AGA - vt issue #16

Vaikimisi kõigile avamine eeldab, et X-tee liikmeid saab üldjuhul usaldada.

Võimalik on teha ka "ukse" ja doorkeeper-iga lahendus. Tehniliselt X-tee nn grupi - DHX kasutajate gruppi - loomise kaudu. Menetlus oleks:
1. RIA kui X-tee haldaja loob X-tee liikmegrupi "DHX kasutajad"
2. Asutus, kes on valmis DHX-i kasutusele võtma, esitab taotluse (ITAO - Liivi ja/või RIA)
3. <võimalikud tehnilised vm kontrollid>
4. RIA lisab asutuse X-tee liikmegruppi "DHX kasutajad"

Sellisel juhul peame ette kirjutama, et teenus avatakse ainult grupile "DHX kasutajad".

Tunnistagem, et sellises korras on oma administratiivne võlu: DHX-i rakendamise protsess oleks jälgitav ja administratiivselt kontrollitav.

Võib küll öelda, et asjatu bürokraatia, kuid kui inimestele liiga vähe struktuuri ette anda, siis nad kaotavad orientatsiooni?

**Comment by PriitParmakson** [comment]
Küsimuses DHS arendajalt (IS):

Aga githubi dokumentatsioon viitab x-tee kasutamisele selleks, siis mul väike kõhklus ja segadus. Seda just xtee ver 6 valguses, millega olemas värske kogemus.

Kui sain õigesti aru, siis iga DHS on xtee jaoks fikseeritud nimega subsystem (dhs), mis pakub ühte fikseeritud nimega teenust. Kena.
Turvaserveris tuleb avada see teenus kõigile saatjatele, muidu saab saatja lihtsalt veateate. Saatjaid tuleb ajas juurde (nad võivad olla hetkel olemas, nt KOV-id, aga nad tekivad x-tee ver 6-le vaikselt juurde. Seega, kas saan õigesti aru, et asutuse turvaserveri haldurile ja DHS-ide tugiisikutele on tagatud igapäevane pidev töö?

Või on selleks mingi nõks?
Tsentraalset õiguste jagamist ei saa olla vastavalt xtee enda turvapoliitikale (asutuse turvaserveri admini ei tohi üllatada, et keegi RIA-st on mingil hetkel teinud tema hallatavas serveris lahti mingi teenuse mingile tarbijale -- vb pole see teenus DHS teenus vaid midagi hoopis tundlikemate andmetega).

Ma olen natuke segaduses selles osas. Kas saaks täpsustusi, kuidas x-tee õigused tekivad?
**
Ja kui igakord tuleb uus x-tee v6-le liituja, siis ta võtab ka DHX teenuse kasutusele?
**
TO DO: Analüüsida ja täpsustada.

**Comment by EneliJarve** [comment]
No põhimõtteliselt ongi ainult kolm võimalust:
1)  DHX keskust ei ole ja tuleks avada päringud kõigile (X-teel on juba kõigi X-tee liikmete globaalne grupp olemas).
2)  Igaüks ise haldab oma turvaserveris õigusi ning avab liigipääsu vaid neile kellega peab suhtlema.
3)  Keegi haldab DHX liikmete nimekirja, ning on ainult loogiline et seda teeb RIA (keskserveri ja RIHA pidaja).

## 

Vitali Stupin
Riigi Infosüsteemi Amet
Arhitekt

**Comment by PriitParmakson** [comment]
**JS**: 
Tehniliselt seisneb X-tee teenuse "kõigile avamine" teenuse avamises globaalsele grupile "allconsumers"
