### ISSUE TITLE
Kas DHX-il on ka versiooninumber?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#24]
Vrdl CSS 3, HTML 5 jt.

Ei ole, aga see peab tekkima.

Kirjandus: RFC 6709 [Design Considerations for Protocol Extensions](http://www.ietf.org/rfc/rfc6709.txt)  (2012), jaotis 4.1 Version Numbers.

**Comment by PriitParmakson** [comment]
Vrdl [HTTP protocol versioning](https://tools.ietf.org/html/rfc7230#section-2.6): "The  protocol version as a whole indicates the sender's conformance with the set of requirements laid out in that version's corresponding specification of HTTP."

**Comment by tormi** [comment]
Versioonid (sh praegune _v 1.0.4_) tuleks GitHub'is viidatavaks teha [reliiside](https://github.com/e-gov/DHX/releases) abil.
