### ISSUE TITLE
DVK pakkus detailset statistikat dokumendivahetuse kohta. Mis sellest saab?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#25]
Väljatöötamisel on X-tee monitooringulahendus. Statistikat hakatakse tootma ja tarbima selle kaudu.

**Comment by hillar** [comment]
arhitektuuri dokument on seal https://github.com/vrk-kpa/xroad-public/blob/master/src/doc/Monitoring-architecture.md
