### ISSUE TITLE
Kas on kuidagi takistatud, et X-tee liige ei võta DHX/sendDocument kasutusele teises tähenduses?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#26]
Segaduse tekkimise võimalus on pigem teoreetiline. Siiski peaks tagama, et segadust ei saaks tekkida. Pigem organisatsiooniliste kui tehniliste meetmetega, sest X-teel ei ole "kindla tähendusega nimede" (_assigned names_) mehhanismi. X-tee liikme alamsüsteemi DHX registreerimisel RIA-s tuleks kontrollida, et X-tee liige peab silmas DHX-i, mitte midagi muud.

Kirjandus: [RFC 6943 Issues in Identifier Comparison for Security Purposes](http://www.ietf.org/rfc/rfc6943.txt).

**Comment by martinpaljak** [comment]
Sarnaselt IP võrkudele ei keela keegi SSH-d jooksutada port 80 peal ja HTTP-d port 22 peal. Aga enamasti seda ei tehta. Piisab kusagil relevantses dokumentatsioonis (x-tee?) mainida, et "teenus nimega XXX on reserved" ja kõik.
