### ISSUE TITLE
Kas "kapsel" muutub?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#31]
Eesmärk on "kapslit" võimalikult vähe muuta.
Lahendamist vajavad küsimused:
- Elektroonilise andmevahetuse metaandmete loend on nn semantiline standard, ei anna konkreetse masinloetava esituse süntaksit. Masinesituse süntaks on kirjeldatud DVK spetsifikatsioonis. DVK spetsifikatsioon kaob ära. "Kapsli" tehniline spetsifikatsioon tuleb tekitada - kas Elektroonilise andmevahetuse metaandmete loendi juurde või eraldi dokumendina või DHX-i osana.
- "Kapsli" võib hoida jõuda muutumatuna. Osa välju langevad kasutusest välja, osade semantika kohendub. Mingi aeg tuleks siiski kapsli täiendamine ette võtta.

Vt ka https://github.com/e-gov/DHX/blob/master/files/Mis%20mille%20sees%20k%C3%A4ib.md

**Comment by EneliJarve** [comment]
DHS arendajate kommentaar kapsli osas:  Kapsel on vigane ega ei vasta tegelikkusele. Näiteks nõutakse seal kohustusliku väljana juurdepääsupiirangu lõpukuupäeva, kuid teatud juhtudel on see sündmuslik, nt koosoleku toimumiseni või seaduse vastuvõtmiseni, seega ei saa antud väli kohustuslik olla. Tuleks käivitada ka projekt kapsli ülevaatamise osas ehk siis vaadata mitte ainult transpordikihti vaid ka semantilist kihti.

**Comment by tonupold** [comment]
Kapsli versiooni määrab ära selle nimeruum. 
Versioon 2.1 XML-is on see: targetNamespace="http://www.riik.ee/schemas/deccontainer/vers_2_1/"

Seega eraldi kapsli versiooni määravat välja DHX protokolli vaja ei ole.

Hetkel protokoll ülteb et "Vastuvõttev süsteem PEAB kontrollima, et dokument tuli nõuetekohases kapslis."  Viidete all on viide versioonile 2.1.

Hajusa süsteemi korral kerkib aga see probleem et uue kapsli versiooni (näiteks 3.0) kasutusele võtt muutub väga-väga keeruliseks. Sest osad saatjad toetavad vana versiooni, osad uut. Samuti osad vastuvõtjad toetavad vana versiooni, teised uut. 

Hea oleks kui DHX enda versioon ei muutuks, kui kapsli versiooni muutub.
Aga sel korral DHX siiski peaks spetsifitseerima, mis seoses uue kapsli kasutusele võtu korral ikkagi toimub? 

Siin vist ka variante mitmeid (aga kõik oma vigadega või teevad protokolli keerukamaks):
- Kui uus UK (Universaal komponent) on kohustuslik, siis kõik vastuvõtjad peavad uuendama (korraga) UK komponendi, mis kasutab kapsli uut versiooni
- Nõuda et iga saatja peab oskama saata kahte viimast versiooni (näiteks 2.1 ja 3.0). Sel korral vastuvõtjate üleminek ei pea toimuma koheselt (vaid piisavalt suure ajaraami piires). Samas saatjad peavad uut versiooni toetama "koheselt" (ülemineku ajaraami ei ole).
- Nõuda et iga vastuvõtja peab oskama vastu võtta kahte viimast versiooni (näiteks 2.1 ja 3.0). Sel korral vastuvõtjad peavad uut versiooni toetama "koheselt" (ülemineku ajaraami ei ole).
- Variant et Vastuvõtja kui ei toeta veel uut versiooni annab vea "Kapsli versioon pole toetatud". Saatja salvestab selle vea ning uuesti ei saadagi. Sel korral dokumendi saatmine teatud asutustele (ülemineku ajaraami jooksul) ei ole enam võimalik (Kapslite versioonide mitteühilduvuse tõttu).
- Pakkuda kapslite versioonide vahel transleerimise teenust või komponenti (heal juhul oleks see võimalik XSLT abil). Samas ei saa vist eeldada et see on alati võimalik, sest Kapsli uus versioon võib lisada kohustuslikke välju, mida vana ei sisalda. Variant on Kapsli uue versiooni välja töötamisega nõuda ka koheselt transleerimise komponendi välja arendamist, siis Kapsli uue versiooni väljatöötajad peavad arvestama et edasi-tagasi transleerimine peab olema võimalik.

**Comment by tonupold** [comment]
Hetkel olemasolevate kapsli  1.0 ja 2.1 versioonidega on iga versioon on defineerinud uue namespace:
- 1.0 korral http://www.riik.ee/schemas/dhl-meta-manual, http://www.riik.ee/schemas/dhl-meta-automatic, http://www.riik.ee/schemas/dhl
- 2.1 korral http://www.riik.ee/schemas/deccontainer/vers_2_1/

Kui kapsli versiooni muutus tulevikus (näiteks 2.1->2.2 ) ei ole nii radikaalne siis soovitatakse eristada namespace ja version. St et lisada kapslile version atribuut (hetkel seda ei ole) ning defineerida Kapsli laiendatavus kasutades schemas  xs:any, xs:anyAttribute, mustUnderstand elemente.

https://msdn.microsoft.com/en-us/library/ms950793.aspx

> Version Numbers vs. Namespace Names
> An XML format should use version numbers to differentiate between different versions of the format, preferably in a version attribute on the root element of the format. The major and minor versioning scheme from traditional software development practices should be used to help users identify compatibility between versions in a straightforward manner. If the XML format is namespace qualified, then the namespace name should be the same between minor versions and should be changed with major versions.

**Comment by tonupold** [comment]
Ettepanek on disainida Kapsel ümber selliselt et seal oleks toetatud  XML extensibility (XML schemas xs:any, xs:anyAttribute, mustUnderstand kasutamine) ja lisada "version" atribuut.

See tagaks et vajadusel oleks Kapsli formaat täiendatav, nii et see on tagasiühilduv ja edasiühilduv (vanad versiooni kasutavad süsteemid võivad ignoreerida uus elemente) sama või täiendava(te) nimeruumide piires.  Või radikaalsemal juhul määraks kasutatav "version" number ja mustUnderstand atribuut ära, et uus versioon ei ole tagasi ühliduv (aga nimeruum jääks samaks)
