### ISSUE TITLE
Mitmele adressaadile korraga saatmine

### ISSUE THREAD

**Issue by tonupold** [e-gov/DHX#32]
DVK korral võis Kapsel sisaldada mitu adressaati. Iga adressaat käis DVK-st eraldi receiveDocuments teenusega küsimas.

DHX korral kaob keskne postkast. Seega peab muutuma ka mitmele adresaadile saatmise loogika.
Ilmselt saatja peab ise sama Kapsli igale adressaadile eraldi saatma. Saatja peab arvestama et mõni adressaat võib tagastada vea. Seega saatja (kasutajaliidese) realisatsioon võiks olla selline et saadetud dokumendi iga adressaadi korral oleks näha kas dokument võeti vastu või tagastati viga.

Uus UK võiks mitmele adresaadile saatmist lihtsustada, niimoodi et võtab DHS-ilt vastu kapsli üks kord ja teostab ise edasi saatmised mitmele adressaadile.

**Comment by PriitParmakson** [comment]
Jah, need on head kaalutlused.

**Comment by PriitParmakson** [comment]
Masspostitused on ühest küljest vajadus, teisest küljest _corner case_.
Masspostituse teenusele ei ole  DHX-i praeguses kontseptsioonis head kohta. Mis ei tähenda, et keegi ei võiks seda teenust pakkuda - ka nt UK.

**Comment by PriitParmakson** [comment]
Vt lahendus #6
