### ISSUE TITLE
Kas protokoll on laiendatav?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#34]
Laiendatavus on oluline. Vrdl [ühe protokolli kriitika](http://vasters.com/clemensv/2014/06/02/MQTT+An+Implementers+Perspective.aspx): 

> "a protocol design that sets the clock back at least 20 years, while the rest of the distributed systems community has made extensibility and Postel's robustness principle driving considerations for practically all modern protocol designs.

"Custom message metadata extensibility". 

Sõnumivorming ei tohiks olla "non-extensible locked box".

**Comment by tonupold** [comment]
Protokolli laiendatavuse mõistmiseks võib improviseerida mida sellega teha tahetakse:
- Praegu on spetsifitseeritud puhtalt peer-to-peer saatmine. Kas võiks tekkida vajadus keerukama hajusa saatmismudeli jaoks ? Kui on, siis võib see tingida täiendavate "custom header" tüüpi väljade kasutamise, mis määravad ruutimise/puhverdamise vms lisainfo. Lisaks kas need "header" väljad spetsifitseerida X-tee request headerina või DHX sendDocuments SOAP teenuse väljadena?Vahendamine juba klassfitseerub keerukama saatmismudeli alla ja seal vahendatava kood on üks selline ruutimise väli. Ehk siis küsimus: kas üldistada vahendamise loogikat?
- Kas soovitakse saata midagi muud kui DVK kapsel?  Kui on näha vajadust, siis sendDocuments teenuses peaks spetsifitseerima "mime-type" tüüpi või sarnase loogikaga välja. Kapsel ise on hetkel XML ja Kapslile endale hetkel mime-type defineeritud ei ole (mis eristaks seda teistest XML-idest).
- Kas soovitakse saata täiendavat tehnilist või ärilist lisainfot, sellist mida kapsel hetkel ei võimalda saata? Hetkel on näha et üks selline täiendav info on "kaust" (see on pigem ruutimise tüüpi info, mitte äriline).  Kas on veel midagi?  Kas peaks üldistama lisainfo väljade defineerimise (XML extensible moel)?

**Comment by tonupold** [comment]
XML Extensibility kohta:
https://msdn.microsoft.com/en-us/library/ms950793.aspx

> The Difference Between Versioning and Extensibility
> An XML format should be both backward and forward compatible. It should be backward compatible in that the new versions of the format should also be valid instances of older versions of the format, and thus not break any consumers of the original format. It should be forward compatible in that older versions of the format should also be valid instances of newer versions of the format, so old producers can work with consumers of the new format. 
> 
> Versioning differs from extensibility in two broad ways. The first major difference is that versioning mechanisms must support change in a linear fashion, while extensibility mechanisms support change in a concurrent fashion. A versioning mechanism must define a mechanism to create a version 1, a backward compatible version 2, a backwards compatible version 3, and so on. 

http://www.xml.com/lpt/a/2003/12/03/versioning.html
