### ISSUE TITLE
representationList kehtivusaegadega?

### ISSUE THREAD

**Issue by aleksei-kokarev** [e-gov/DHX#35]
Võib olla oleks mõistlik lisada representationList teenuse vastusesse ka kehtivusajad(ehk millal vahendamine algab ja lõpeb). Mõtlen et see võiks olla abiks et vigu vältida tulevikus. Ka teenustepakkujatele on see vist lihtsam - pärast lepingu sõlmimist võib vahendatava kohe lisada representationListi ja unustada, kuna lepingu alguskuupäeval vahendamine automaatselt algab ja lepingu lõppkuupäeval automaatselt lõpeb.

**Comment by PriitParmakson** [comment]
Jah, see on väga hea mõte. Palun tehke nii etalonteostuses. Täiendan ka vastavalt protokolli kavandit.

**Comment by PriitParmakson** [comment]
Kas kehtivusaja mõlemad otspunktid peavad olema määratud?

**Comment by aleksei-kokarev** [comment]
algus peaks olema. aga lõpp võiks olla tühi, mis tähendab et ilma tähtajata

**Comment by PriitParmakson** [comment]
Toetan
