### ISSUE TITLE
DHX „aadressiraamat“

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#41]
Luua tööriist, mille abil hajusale dokumendihaldusele ülemineku erinevad osapooled saavad ülevaate kes on juba DHX-i võimekuse loonud.

VAJADUS
Avaliku sektori üleminek detsentraliseeritud dokumendivahetusele algab plaanide kohaselt 2017. a. Erinevad sihtrühmad (asutused, arendajad, teenusepakkujad, ITAO) hakkavad meie poole pöörduma küsimustega:
- kes on DHX-i vahendajad?
- millised asutused on DHX-i vahendajate kliendid?
- kes asutustest on DHX-ile juba üle läinud?

Vajame jooksvat ülevaadet ülemineku seisust.
Vajalik teave sisaldub mitmes allikas: X-tee globaalses konfiguratsioonis, DHX-i vahendajate poolt X-teel publitseeritavates vahendusnimekirjades ja osalt ka RIHAst. Puudub lihtne viis selle teave kiireks kokkusaamiseks ja inimesele esitamiseks.

ETTEPANEK
Luua lihtne tööriist, mis pöörduks X-tee globaalse konfiguratsiooni ja X-teel publitseeritavate DHX-i vahendusnimekirjade poole, koguks sealt teabe ülalnimetatud kolmele küsimusele vastamiseks ning esitaks veebiliidese kaudu inimkasutajale. Tööriista põhikasutajaks oleksid RIA teenusehaldurid ja ülemineku koordinaator, kes kasutavad teavet erinevate sihtrühmade nõustamiseks, probleemide lahendamiseks, üleminekuprotsessi seireks ja statistika andmiseks dokumendihaldust koordineerivale üksusele ITAO-le. Tööriist peaks olema konfigureeritav nii, et teenuse saaks avalikult avada. (X-tee globaalne konfiguratsioon on tehniliselt avalik, DHX-i vahendusnimekirjade avalikkuse kohta tuleb seisukoht kujundada.) 
Terminoloogia: Tööriista abil esitatav nimistu on sisuliselt DHX-i „aadressiraamat“. 

EI OLE SKOOBIS
DHX-i „aadressiraamatut“ ei pakuta masinloetavalt. DHX-i rakendav infosüsteem peab, DHX protokolli kohaselt, dokumendiedastuseks vajaliku aadressiotsingu teostama lokaalselt (https://e-gov.github.io/DHX/#74-lokaalne-aadressiraamat).
Tööriist pakuks ainult hetkeseisu teavet. Ajalugu võib olla vajalik, eelkõige DHX-i vahendajatega seotud probleemide ja järelevalve teostamiseks. Seda oleks siiski tunduvalt raskem teostada, vajadusel saab pöörduda X-tee logide poole.  

TEOSTUS
Teenus on suunatud inimkasutajale (DHX-i planeerijale, arendajale, haldajale, dokumendihalduse koordinaatorile). Käideldavusnõue on madal. 
Tööriista programmeerimiseks vajalikud tarkvarakomponendid on DHX etalonteostuse käigus juba loodud. Kokkupanemise maht on väike.
Tööriistaga ei looda uusi andmeid, andmebaasi ei vaja.
Analüüsi vajab küsimus, kas DHX-i aadressiraamat peaks tervikuna või osaliselt olema avalik. Kui mitte, siis on vaja autentimist ja pääsuhaldust.

**Comment by andreskytt** [comment]
Mõistlik mõte. Teeks jällegi kahes etapis: masinloetavalt ja seal peal asuva UIga.

**Comment by PriitParmakson** [comment]
Uus, detailiseeritud lahtikirjutus: https://github.com/e-gov/DHX/blob/master/docs/DHX-aadressiraamat.md. Kommentaare võib ikka siin anda.

**Comment by tormi** [comment]
Kas RIHA't üldse millegi jaoks kasutatakse? ;)

**Comment by PriitParmakson** [comment]
Kasutavad inimesed. Masintöödeldavalt RIHA teavet ei paku, see on tõsine probleem, sellega tegeleme. Vt https://e-gov.github.io/RIHA-API/Ylevaade.html.

**Comment by tormi** [comment]
> sellega tegeleme

:+1:

**Comment by PriitParmakson** [comment]
Täiendatud (https://github.com/e-gov/DHX/blob/master/docs/DHX-aadressiraamat.md):
- kuvatakse ka muutused (kahe viimase faili diff)
- aadressiraamatu koostamine kasutaja "nupuvajutuse" peale - ei võeta skoopi

**Comment by PriitParmakson** [comment]
Andres Kütt:   Ma teeks nii, et too kataloog oleks JSONi formaadis ning et veebis oleks lisaks ka HTML+CSS+JS, mis oskab seda kataloogi näidata. Raporteerin issuena või pull request vms? Muide, sihuke asi http://asciiflow.com/ . Täitsa tore vahend tekstiliste diagrammide tegemiseks, neid saab siis kenasti githubis MDga segamini hoida ja versioneerida. http://ditaa.sourceforge.net/ oskab nende pealt päris pilte ka joonistada. Kui ma x-tee mustrikataloogi üles korjan uuesti siis ilmselt hakkan selliseid asju kasutama.
