### ISSUE TITLE
Kas asutusel võib olla mitu vahendajat?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#42]
Protokoll ei keela seda. Küll aga tekib küsimus, mis oleks mitme vahendaja mõte? DHX ei paku saatjale teavet, millega too saaks otsustada, kummale dokument saata. Üheaegselt mitme vahendaja olemasolu võib viidata sellele, et vahendaja vahetamisega on midagi sassi läinud - asutus on lisatud uue vahendaja vahendusnimekirja, vana ei ole aga asutust eemaldanud. Siiski ei saa seda alati käsitada veaolukorrana.

**Comment by tormi** [comment]
Dokumendihaldus võib vabalt valdkonnapõhistes rakendustes toimuda, näiteks KOV-idele EHR ehitusvaldkonna vahendajana.
