### ISSUE TITLE
Mis saab e-arvetest?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#43]
_Käesolev issue on mõeldud e-arvetega seonduva arutamiseks. Hoiame arutelu siin, siis jääb jälg kõigile huvilistele nähtavaks!_ **RIA poolt oleme koostanud juhendi [E-arved DVK-s üleminekuperioodil](https://github.com/e-gov/DHX/blob/master/docs/E-arved.md). Juhend on praegu veel kavandi seisuses, kuid valmides peaks andma ammendavad vastused kõigile osapooltele, kelle e-arvemajandust DHX-ile üleminek ja DVK sulgemine puudutab. Palume arutelus osalejatel sellega tutvuda. Kõik küsimused, arvamused ja ettepanekud on teretulnud. Aitäh!**

**Comment by PriitParmakson** [comment]
Kaks küsimust DVK kapsli v 2.1 kohta.

1  Vanas kapslis on arvete liigutamisel  väli

``` xml
 <dhl:metainfo><ma:dhl_kaust>/ARVED</dhl:metainfo></ma:dhl_kaust>
```

, kas uues kapslis peaks olema sama tähendusega

``` xml
 <DecMetadata><DecFolder>/ARVED</DecMetadata></DecFolder>
```

2  Kui kasutada varianti, et arve suunata DVK-võimelise asutuse registrikoodile eesmärgiga see edastada mitte-DVK-võimelisele registrikoodile, siis milline oleks kõige parem selle tegeliku saaja registrikoodi edastamiseks? Kas võiks näiteks olla `DecFolder` väljal `/ARVED/12345678` ?
Sellega saaks lahendada Fiteki ja Omniva  poolt arvete edastamine mitte-DVK-võimelistele Amphora kasutajatele, edastades nende arved Interinxi DVK-sse ja lisades DecFolder või siis vana kapsli korral dhl_kaust väljale tegeliku saaja registrikoodi.

tervitades
Ingmar [Pappel]

**Comment by PriitParmakson** [comment]
Ingmar,
1. Täpselt nii ongi mõeldud. Vt e-arvete juhendi [3.2 Kapsli v2.1 kasutamine E-arvete saatmiseks DHX protokollis](https://github.com/e-gov/DHX/blob/master/docs/E-arved.md#32-kapsli-v21-kasutamine-e-arvete-saatmiseks-dhx-protokollis).
2. Teisele küsimusele palun vastata Tõnul meie arenduspartnerist BPW.

**Comment by ingmarp** [comment]
Tänan!
E-arve 1.2 standardis on ette nähtud pdfi edastamise võimalus XMLi sees, mittekohustuslik element AttachmentFile semantikaga "Arve pildi kajastamine. Kasutatakse BASE64 kodeerimist ja edastatakse arve pilt PDF formaadis".
Küsimus: kas oleks soovitav järgida ülalviidatud "3.2 Kapsli v2.1 kasutamine E-arvete saatmiseks DHX protokollis" toodud kuju, kus on kaks file elementi, ühes sisaldub XML ja teises pdf. Ning kas sellisel juhul oleks soovitav ka XML sees olev AttachmentFile täita BASE64 formaadis pdf-iga ehk siis pdf võiks esineda  sõnumis kaks korda ning mõlemal korral mittekohustuslikuna?

**Comment by PriitParmakson** [comment]
Tõnu vaatab ja vastab. 
Muide, lisasin https://github.com/e-gov/DHX/blob/master/docs/E-arved.md - eelmärkuse koos kahe skeemiga e-arveliikluse kohta.

**Comment by tonupold** [comment]
E-arve PDF edastamise osas (kas DVK 2.1 kapslis eraldi või ainult E-arve 1.2 XML-i sees) peaks arvestama kellel see e-arve edastakase ja kas vastuvõtja suudab e-arve XML-i töödelda.

Nimelt hetkel DVK sees e-arved edastatakse ka tavalistele DHS (Dokumendihaldus) süsteemidele, kes e-arve XML-i tegelikult töödelda ei suuda. Sellisel juhul on hea kui PDF on kapsli sees eraldi manusena, sest siis DHS süsteem (kes suudab töödelda ainult DVK Kapslit) kuvab selle DHS kasutajale PDF dokumendina. Ehk siis sel juhul oleks võimalik arve käsitsi töötlemine PDF alusel, mitte e-arve XML alusel.

Kui arve PDF edastakse ainult E-arve 1.2 XML sees, siis osad DHS süsteemid ei suudaks neid kasutajale loetaval kujul kuvada ja dokument jääb üldse töötlemata, Need DHS süsteemid peaksid täiendavalt juurde arendama ka E-arve XML-i parsimise loogika.

Lisaks mulle tundub, et PDF-i esitamine nii Kapsli kui ka e-arve XML-i sees on võimalik ja mõistlik. Ainuke probleem siin tundub andmemahu kasv, mis e-arvete korral ei ole tohiks olla märgatav, sest arve PDF dokumendid enamasti 1-2 lehelised (väiksed).

**Comment by PriitParmakson** [comment]
Kas võiks näiteks olla DecFolder väljal /ARVED/12345678 ?
- Kui Interinx võtab kasutusele DHX-i, siis saab Interinx tegutseda oma Amphora klientide DHX vahendajana.
- Kui soov on tegutseda DVK-võimekust mitteomavate klientide suhtes vahendajana juba praeguse, "DVK protokolli" raames, siis peaks ikka kasutama e-arve XML-is olevat e-arve (lõpp)adressaati. /ARVED/12345678 kasutamine võiks küll hõlbustada arve marsruutimist Interinxi süsteemis, kuid tähendaks loogika muutmist DVK-s, sh üleminekuperioodil. See muutmine ei oleks lihtne. Muuhulgas peaksime DVK-s tagama, et DHX-ga DVK-sse sissetulnud 12345678-le adresseeritud dokumendi tunneb DVK ära kui arve, teeb kindlaks, et 12345678-le saadetud dokument tuleb edastada Interinx-ile (mille alusel DVK seda kindlaks teeks?) ja moodustama väärtuse /ARVED/12345678 välja DecFolder. Tahame hoida DVK äriloogika muudatused minimaalseina, tehes ainult DHX-le üleminekuks vajaliku.
