### ISSUE TITLE
I need client-security server example

### ISSUE THREAD

**Issue by 729234500** [e-gov/DHX#45]
i don't know 
How user client is connected to the security server?
give me a example please!!!!! 

thanks for you!!!!

**Comment by PriitParmakson** [comment]
Please contact the X-Road centre https://www.ria.ee/en/x-road.html.

**Comment by 729234500** [comment]
thanks 
because of i am so stupid . i am not found it
could you give me expatiation  location please .

**Comment by VassilMarjunits** [comment]
@729234500 try on page 6, this will give you idea about X-road and security server 
http://x-road.ee/docs/eng/security_server_users_guide.pdf

**Comment by 729234500** [comment]
OK   It's great. Also thanks for you. But ,I dont' need it 
I need Application(Information system? ) to X-road security server configuration files . And The security server should be done about it?

**Comment by 729234500** [comment]
@VassilMarjunits  OK It's great. Also thanks for you. But ,I dont' need it
I need Application(Information system? ) to X-road security server configuration files . And The security server should be done about it?

**Comment by VassilMarjunits** [comment]
@729234500 if you looking for some example of "information system", wich can operate "behing" security server? Then take a look on thous components "X-Road Test Service" and "X-Road Test Client".
https://github.com/jointxroad/components/blob/master/component_descriptions.md#x-road-test-service

**Comment by 729234500** [comment]
@VassilMarjunits  Ok  thanks  Let me try it .thankyou very much

**Comment by 729234500** [comment]
@VassilMarjunits   I watched these examples .I don't know  The real information system is how to connect to the x - road security server? I need your  help . 
A demo  .Very urgent

**Comment by 729234500** [comment]
@VassilMarjunits   If you don't help me
Maybe  I  will be unemployment
