### ISSUE TITLE
Mis saab DVKs peetavast registrist asutuste allasutuste kohta?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#7]
(küsitud kohtumisel arendajatega 17.03.2016)
Jah, DVK pakub asutustele võimalust publitseerida oma allasutuste nimekiri. Allasutuste nimekirju saab DVK-st X-tee teenuse abil pärida. DHS-ides kasutatakse seda dokumentide adresseerimisel.

DHX-i puhul tuleks sama teave võtta RKOARR-st. RKOARR-is on allasutuste andmed kõige autentsemal kujul. RKOARR viiakse üle Äriregistri juurde ning täiendatakse RKOARRi X-tee teenuseid. Selline andmekasutus vastaks riigi IT koosvõime ja AvTS nõudele.

Miinuseks on see, et DHS-is tuleks mõned asjad ümber teha. See on üks asi, mida võiks lahendada kavandatav Universaalne tarkvarakomponent?

**Comment by aleksei-kokarev** [comment]
ei saanud täpselt aru miks DHS ise ei saa pöörduda RKOARR-i? Mis kasu annab UK kasutamine, kas vähem ümbertegemist DHSis?

**Comment by PriitParmakson** [comment]
Täpselt nii, UK ei peaks vahendama RKOARR (2017. a alates Äriregistri) teenuseid. DHS peaks vajadusel ise RKOARR-i (Äriregistri) poole pöörduma.
Kuid me peame DHS-de kasutajatele ja arendajatele selgitama, mida DHX neile kaasa toob.
Vaja on selgitada, milliseks kujunevad RKOARR-ist Äriregistrisse üleviidavad teenused. Teeme selle kohta RIK-ile päringu; vastust saate kasutada tehnilises analüüsis ja üleminekukava koostamisel.

**Comment by EneliJarve** [comment]
RIK-ist vastati ja saadan Alekseile meilitsi ka RIK-i lähteülesande antud arendusele, äkki saate sealt rohkem informatsiooni ja ülevaadet, et mida nende arendaja seal tegema hakkab.

Teenustest ( Andres Moks, RIK) : 
Rkoarr hakkab kasutama äriregistri teenuseid st teenused hakkavad väljastama ka rkoarr andmeid.
Rkoarril endal on ka kaks teenust, nende suhtes analüüsib  RIK-i arendaja, kas ja millises mahus katavad olemasolevad teenused nende andmeväljundeid. Vajadusel tehakse uued teenused ÄR juurde.
Arenduste üldine lõpptähtaeg on 15.11.2016.
