### ISSUE TITLE
Kas universaalse tarkvarakomponendi võiks teha SOAP <-> Restful teisendajana?

### ISSUE THREAD

**Issue by PriitParmakson** [e-gov/DHX#9]
(küsitud kohtumisel arendajatega 17.03.2016)

See on huvitav mõte, mis vajab kaalumist.

**Comment by aleksei-kokarev** [comment]
ma mõtlen et ei pea probleemiks olla teha nii et UK suhleb Xtee-ga kasutades SOAP. Aga DHS-i jaoks võib pakkuda nii SOAP kui REST teenusi ja iga DHS saab ise otsustada milliseid kasutada.

**Comment by PriitParmakson** [comment]
See oleks väga hea lahendus. Võib-olla on kasuliks heita pilk soomlaste (kes kasutavad X-Road-i oma rahvusliku andmevahetuskihi tuumana) tehtud [X-Road REST Gateway-le](https://github.com/educloudalliance/xroad-rest-gateway).
Kui suhtlete DHS-de arendajatega, siis palun küsige, kas nad eelistaksid REST-i või SOAP-i. Kuid REST tuleks teha niikuinii, sest protokolli võivad tulevikus hakata kasutama uued, REST-i kasutavad DHS-id.
